### ISSUE TITLE
virksomheder på husnummer mangler resultater

### ISSUE THREAD

**Issue by rastermanden** [Septima/OneDoor#10]
https://onedoor.test.septima.dk/#/septima/kortdage/Dawa/adresse/0a3f507c-cce5-32b8-e044-0003ba298018/Septima.Search.CvrVirksomhederForAdresseProvider_1

**Comment by Ellebjerg** [comment]
Søgning på adressen (Hvidovrevej 278) i CVR viser 9 aktive CVR-numre.

**Comment by rastermanden** [comment]
Det er rettet på version 1.4.50

 Der er nu en helt ny cvrsearcher der både søger i produktionsenheder og virksomheder
