### ISSUE TITLE
Søgning på vejkode

### ISSUE THREAD

**Issue by rastermanden** [Septima/OneDoor#11]
Kan man søge på vejkode istedet for vejnavn ?

Vejkode er firecifret tekst

**Comment by Ellebjerg** [comment]
Det ville være super med en mulighed for at søge på vejkode eller vejnavn og så få vist hele vejen. Det kunne fint være et søgeresultat med forskellige relevante faner, fx adresser, virksomheder med adresse til vejen..., men det vigtigste er muligheden for at få vist hele vejen, i hvert fald i Hvidovrekortet.

**Comment by rastermanden** [comment]
Hvis I har egne veje i egen lokal postgres database, er det en god ved at gå med brug af pg_index (en extension til postgres udviklet til Septima)

**Comment by MichaelDavidKnudsen** [comment]
Kan man ikke bruge DAWA's api?
Fx. kald som dette: https://api.dataforsyningen.dk/vejstykker/0167/4032?format=geojson

**Comment by rastermanden** [comment]
DAWA har kke veje, hvor der ikke er adresser tilknyttet
Ved brug af egne veje, kan det gøres med pg_index uden ekstra kodearbejde.

**Comment by rastermanden** [comment]
Hvis I har veje i egen database, kan det gøres ret enkelt

**Comment by Ellebjerg** [comment]
Vi kan godt lave en tabel med veje i PG, men det ville være mere hensigtsmæssigt med en mere generisk løsning.
Hvad med GeoDanmark. Der er vejkode på.

**Comment by rastermanden** [comment]
Det er hvis det haster. Den generelle løsning går der lidt tid før vi kan løse

**Comment by Ellebjerg** [comment]
Så tænker jeg, at vi venter. Det er irriterende ikke at kunne søge på veje, men vi har ikke data i databasen, og jeg kan ikke bruge tid på det lige p.t.

**Comment by MichaelDavidKnudsen** [comment]
Jeg er helt enig med Lars. Vi må afvente den generiske løsning.

Vi undrer os over, at det ikke skulle være muligt, at få vist en vej uden adresser. Det ser ud til at virke med denne url: https://api.dataforsyningen.dk/vejstykker/0167/0021?format=geojson

**Comment by rastermanden** [comment]
@klavspc vender tilbage med yderligere info

**Comment by furesoe** [comment]
@rastermanden  Kan denne ikke lukkes, da det håndteres i andet issue?

**Comment by klavspc** [comment]
Der kan nu søges på vejkode. Ved eksat match på vejkpode vises vejen(e) i listen
