### ISSUE TITLE
Dybe link til filarkiv fra OneDoor

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#14]
Link til den interne del af FilArkiv. 

Link via et ejendomsnummer

https://hvidovre.filarkiv.dk/Link/Search/Ejendomsnr/100007

Hvor 10007 er ESR-ejendomsnummeret. Kommunekoden skal ikke angives, da systemet forventer det er Hvidovre Kommune.

Link via en matrikelreference

https://hvidovre.filarkiv.dk/Link/Search/Matrikelnr/21851-1a

Hvor der skal angive en landsejerlavskode, en bindestreg (-) efterfulgt af matrikelnummeret. Matrikelnummeret er cifre + litra som vist ved eksemplet.

Link via en adresse

https://hvidovre.filarkiv.dk/Link/Search/Adresse/0029-7

Hvor der skal angives en 4-cifret vejkode, en bindestreg(-) efterfulgt af husnummeret. Husk altid 4-cifret vejkode.

**Comment by klavspc** [comment]
Link fra jordstykke og husnummer findes allerede (`FilarkivLinkForAdresseMatrikelHandler`), som  tager kommunenavn som parameter (Se https://github.com/Septima/spatialsuite-s4/tree/master/tools#s4-jo-filarkiv-link-plugin)

Ishøj ønsker handleren udvidet med link for esr# - Opgaven estimeres til to timer, idet handleren skal refaktoreres til at reagere på ejendom

**Comment by klavspc** [comment]
Genåbn issue, hvis i ønsker link til Filarkiv for esr#. Jeg estimerer det som sagt til et par timer

**Comment by rastermanden** [comment]
Er det denne detailhandler:
- _type: Septima.Search.FilarkivLinkForAdresseMatrikelHandler

**Comment by klavspc** [comment]
Ja, med kommunenavn som parameter (Som det står i deres eksisterende cbinfo-parameter
`<param name="s4.jo.filarkiv.kommunenavn">xxx</param>`)

Se også https://github.com/Septima/septima-search/blob/master/src/js/searchers/detailhandlers/FilarkivLinkForAdresseMatrikelHandler.js#L14-L16
