### ISSUE TITLE
OneDoor i Spatial Suite bør søge i det nye skitse-værktøj og i egne data og ikke længere i arbejdsområder

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#16]
OneDoor i Spatial Suite bør søge i det nye skitse-værktøj og i egne data og ikke længere i arbejdsområder

De nye skitser i Spatial Suite ligger, som en del af temavælgeren, og er i følgende to temagrupper:
Mine skitser / egne skitser og andre brugere skitser / delte skitser

Egne temaer i Spatial Suite ligger, som en del af temavælgeren, og er i følgende to temagrupper:
Mine temaer / egne brugertemaer og andre brugeres temaer / delte brugertemaer

**Comment by klavspc** [comment]
Lukkes - oprettet i s4 således: https://github.com/Septima/spatialsuite-s4/issues/378

@MichaelDavidKnudsen: Du må gerne se på issuet i s4 og vurdere om jeg har formuleret det korrekt
