### ISSUE TITLE
OneDoor i Spatial Suite. På en mindre skræm, eksemplevis 13” bærbar forsvinder søgefeltet ud af skærmen.

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#17]
OneDoor i Spatial Suite. På en mindre skræm, eksemplevis 13” bærbar forsvinder søgefeltet ud af skærmen.

![image](https://user-images.githubusercontent.com/8234702/152771126-cd0a1d0e-9f36-465a-b1fd-43d23920ee32.png)

**Comment by klavspc** [comment]
Her oprettet https://github.com/Septima/spatialsuite-s4/issues/379

**Comment by klavspc** [comment]
Løst i s4 v 2.14.6 (Downlaod: Se https://github.com/Septima/spatialsuite-s4#basic-installation-and-test)
