### ISSUE TITLE
S4 OneDoor overstyrer med uhensigtsmæssig style

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#18]
Efter at vi er skiftet til OneDoor, er højden på søgefeltet i Hvidovrekortet blevet 42 px, hvor det før var 36 px. Det skyldes muligvis, at vi har sat historik på, men jeg er ikke sikker.

Jeg har tilføjet <file type="css" name="/css/custom/s4.css" />, som vi har stående i s4-plugin-167-all.xml til s4-plugin-onedoor.xml. Nu indlæses søgefeltet med en højde på 36 px, men umiddelbart efter øges det til 42 px. Det er ikke hensigtsmæssigt, da det betyder, at feltet ikke kan være i værktøjsbjælken (panel-middle), og at bunden af det rager ned under panel-brand, som vi har flyttet det til, fordi det ikke kan være i værktøjsbjælken.

Jeg synes, at jeg har oprettet et issue om det i S4, men jeg kan ikke finde det, så I må undskylde, hvis dette er en dobbeltgænger.

Vh Lars

**Comment by klavspc** [comment]
Har oprettet https://github.com/Septima/spatialsuite-s4/issues/377

**Comment by klavspc** [comment]
Har lige nogle uddybende spørgsmål:
Hvilket panel ønsker du søgefeltet vist i?

> Jeg har tilføjet , som vi har stående i s4-plugin-167-all.xml til s4-plugin-onedoor.xml

Hvad har du tilføjet? Kopiér gerne hele din s4-plugin-onedoor.xml ind som kommentar
