### ISSUE TITLE
Finder ikke gældende lokalplan for bygninger / bygningspolygoner

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#25]
OneDoor finder ikke den gældende lokalplan for bygningen (bygningspolygonen).
Der skrives fejlagtigt, at der ikke er fundet nogle lokalplaner for bygningen.

Eksempel på fejlen:
Søger på adressen Bavnevej 2A, 2650 Hvidovre, hvor den korrekt finder lokalplanen: Område omkring "Beringgård".
Men vælges bygningen på Bavnevej 2A, 2650 Hvidovre, så er der ingen lokalplan.

**Comment by rastermanden** [comment]
Gælder det stadig? Kan ikke genskabe her: https://onedoor.test.septima.dk/#/septima/kortdage/DAF/bbr_bygning/83817aa6-a3d0-4285-99f3-41a5df0514eb/Septima.Search.ComposedDetailsHandler_1

**Comment by MichaelDavidKnudsen** [comment]
Nej, den ser ud til at være løst. Dejligt :-)
