### ISSUE TITLE
Uregelmæssige resultater ved søgning på produktionsvirksomheder

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#26]
Vi oplever uregelmæssige resultater på søgninger på produktionsvirksomheder.

Eksempel:
Når vi søger på "Netto" i Hvidovre, så finder OneDoor fem resultater i dropdown-menuen, men giver resultatet "Unexpected error", når man forsøger at få info på en af produktionsvirksomhederne.

Når vi søger på "Fakta" i Hvidovre, så finder OneDoor to resultater, henholdsvis "Fakta 0372" og "Fakta 0409", men når man forsøger, at få vist info for en af produktionsvirksomheder, så viser OneDoor følgende resultat:

![image](https://user-images.githubusercontent.com/8234702/153779441-6e4b5181-87d0-4aa3-8d40-dec11b9b2219.png)

Det ser ud til, at geografien mangler, der mangler i hvert fald punktgeometri  på hovedparten af de viste produktionsvirksomhederne.

**Comment by rastermanden** [comment]
Data fra CVR er ofte mangelfulde ifht. geometri. Vi arbejder på at geokode dem, der mangler geometri fra registeret.

**Comment by MichaelDavidKnudsen** [comment]
Hej Martin
Vi er med på, at adresser i cvr er mangelfulde. Men det er vel kun en del af problemet. OneDoor finder jo virksomhederne og burde vel kunne vise info på dem uden geometri?

**Comment by rastermanden** [comment]
ja, bestemt. Der arbejdes netop nu på at løse det problem også

**Comment by rastermanden** [comment]
Kan du pege på den af de virksomhender, der fejler når du klikker info på dem ?

**Comment by rastermanden** [comment]
I version 1.4.52 har vi en nye cvrsearcher, der bruger et nyt api med bedre data. Der er stadig nogle hvor det ikke kan lade sig gøre at geokode.
Derudover kan man konfugure således, at det kun er produktionsenheder inden for samme kommune. 

Tilsammen vil det betyde at man sjældent vil se ovenstående  i praksis

**Comment by Ellebjerg** [comment]
Den nye cvrsearcher er rigtigt god. Tak!!!
