### ISSUE TITLE
Visning af ejerlejligheder under ejendom

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#27]
Når man søger ind på en adresse og klikker videre til Samlet fast ejendom ville det være godt med en liste over ejerlejligheder på ejendommen. 
Ved søgning på en adgangsadresse kan man se ejendomme (ejerlejligheder) knyttet til adressen, men det ville give et godt overblik over ejerlejligheder, hvis man kunne få en liste med samtlige ejerlejligheder beliggende indenfor en matrikel eller ejendom frem for at skulle søge dem frem husnummer for husnummer.

Vh Lars

**Comment by GISAabenraa** [comment]
Vi tilslutter os 

VH Nicolai,
 Aabenraa Kommune

**Comment by rastermanden** [comment]
Hvis man anvender vores standardkonfiguration for kommuner er det med. Der er også bygninger på fremmede grund

![image](https://github.com/user-attachments/assets/568622a5-b49b-436d-a5ba-b715a8e7eb73)
