### ISSUE TITLE
Tilføj kommunenavn på detaljeside for matrikler

### ISSUE THREAD

**Issue by ChristofferNielsenHofor** [Septima/OneDoor#28]
Når man klikker ind på en matrikel, vises matriklens kommunenummer.
- [x] Vi kunne dog godt tænke os, at der her blev tilføjet kommunenavnet, så der f.eks. kom til at stå 0101 (Københavns Kommune).
- [x] Derudover mener vi, at der ikke burde være komma mellem matrikelnummeret og ejerlavsnavnet på samme side, så der f.eks. kunne stå Matrikelnr. 3942 Udenbys Klædebo Kvarter, København i stedet for Matrikelnr. 3942, Udenbys Klædebo Kvarter, København

**Comment by klavspc** [comment]
@ChristofferNielsenHofor: Dette er to issues og jeg har tilladt mig at redigere din beskrivelse så det er tydeligt

- Kommunenavn - Det er noteret og vil blive taget med, hvis det ikke kræver et nyt opslag
- Komma efter matr# - Det er vores valgte formattering og ikke ualmindelig. Se f.eks. §2.1 i [denne lokalplan](https://dokument.plandata.dk/20_9607930_1569581307622.pdf)

**Comment by rastermanden** [comment]
Kommuenavn kommer med i en kommende version

**Comment by rastermanden** [comment]
![image](https://user-images.githubusercontent.com/1125134/186116969-4da507d7-806a-42d5-8077-b344ea148899.png)

lukkes. Hvis "Komma efter matr#" skal genovervejes, oprettes seperat issue
