### ISSUE TITLE
CVR service i OneDoor er nede / virker ikke

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#29]
Unexpected error
S3Error: invalid json response body at http://g.septima.dk/geoserver/stamdata/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=stamdata%3Aproduktionsenheder&outputformat=json&cql_filter=cvrnummerrelation=35954716 reason: Unexpected token < in JSON at position 0

**Comment by rastermanden** [comment]
Denne er læst og på vej i næste release som kommer snarest

**Comment by rastermanden** [comment]
løst i 1.4.24
