### ISSUE TITLE
Sortering på searcherne - sorteres ikke hensigtsmæssigt

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#30]
Searcherne sorteres ikke intuitivt.
Adresser sorteres som A, Ae, Aa osv. i stedet for at få Æ, Ø og Å i bunden.
![image](https://user-images.githubusercontent.com/38730459/158434687-0ace4089-fc5a-4dd7-b981-5de3dec0cf84.png)

Lokalplaner sorteres ikke alfabetisk.

![image](https://user-images.githubusercontent.com/38730459/158434617-831821f9-b7a3-43c4-9c7e-8b1a6d2660dd.png)

**Comment by furesoe** [comment]
@klavspc:

Dette er stadig et stort ønske. Kan det imødekommes?

**Comment by furesoe** [comment]
@rastermanden 
Jeg kan ikke helt vurdere om det er bedst at sortere på plannavn eller plannummer, men det vil være en stor forbedring, at den blot sorteres efter en kendt identifikator.
Måske er det bedst at sortere på navn så længe, at overskriften blot består at plannavnet. Vi har dog før vendt, at plannummer og plannavn ofte hænger sammen i en planlæggers verden.

**Comment by klavspc** [comment]
Vi skal snart omlægge søgeteknologi for lokalplaner og vil i den forbindelse se på sortering af planer ved den blanke søgning - der er ikke nogen tidshorisont endnu

**Comment by klavspc** [comment]
Issue er oprettet i det system som søgningen skal omlægges til - jeg melder tilbage på dette issue når der ligger en plan

**Comment by klavspc** [comment]
> @klavspc:
> 
> Dette er stadig et stort ønske. Kan det imødekommes?

Resultater fra DAWA sorteres som modtaget fra DAWA - der er ingen planer for omlægning af den funktion

**Comment by rastermanden** [comment]
I den nye løsning med søgning i lokalplaner mod Septima Data-api sorterer vi lokalplaner på plannummer

**Comment by furesoe** [comment]
> I den nye løsning med søgning i lokalplaner mod Septima Data-api sorterer vi lokalplaner på plannummer

@rastermanden
Hvornår implementeres den? Kan jeg tage det i anvendelse?

**Comment by klavspc** [comment]
>Hvornår implementeres den? Kan jeg tage det i anvendelse?

Funktionen er ved at blive udviklet - Vi har planlagt en release slut marts og håber at få den med dér

**Comment by furesoe** [comment]
@klavspc 
Meget fint! Tak!

Kan sortering af adresserne også fikses, jf. https://github.com/Septima/OneDoor/issues/40 ?
