### ISSUE TITLE
Listen over features i seacherne: Kan listen gøres længere?

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#34]
Kan det lade sig gøre at udvide listen fra de ca. 100 forekomster der er nu, til en liste på op til fx 300?

Så ville jeg kunne få fulde lister med foreninger og lokalplaner fx.

![image](https://user-images.githubusercontent.com/38730459/158436864-fb45e25d-04c1-4a20-9e68-7e4974593060.png)

**Comment by rastermanden** [comment]
Vi undersøger lige sagen. Det er ikke helt trivielt, men vi kan komme med et estimat

**Comment by furesoe** [comment]
@klavspc 
Har I kigget på ønsket? Mit eget personlige ønske er at listen udvides til 300, da det vil dække antallet af rækker i flere af mine tabeller. Det er selvfølgelig et lokalt behov - og måske lidt en tilfældighed.
Der kunne dog også være musik i at lave den udvidede løsning. Det tager jeg lige med videre, til den lidt længere bane.

**Comment by klavspc** [comment]
Fra næste version kan man sætte option _singleSourceResultsLimit_ på controller. Den option styrer hvor mange resultater, der maks vises

Default er 100 som altid - så kan man skrue op og ned alt efter hvad ens underliggende konfiguration og brugernes browsere kan klare

```
controller:
  _type: Septima.Search.Controller
  _options:
    blankBehavior: search
    singleSourceResultsLimit: 500

```
