### ISSUE TITLE
Søge på vejnavne med zoom til vejafgrænsningen og markering af vejen

### ISSUE THREAD

**Issue by nice-sonderborg** [Septima/OneDoor#37]
Man kan ikke søge på vejnavne i OneDoor som i S4.
Det bruges af vejfolk og adressefolk som skal søge på veje som ikke har adresser endnu.

**Comment by nice-sonderborg** [comment]
Her er der tale om S4 mod OneDoor - en knap med "Vis helle vejen" efter man har søgt en adresse kunne være en løsning ifølge Klavs.

**Comment by nice-sonderborg** [comment]
Hej Septima - har I et tidshorisont på løsningen?

**Comment by Ellebjerg** [comment]
Vi ser også dette som en væsentlig forbedring, både i Onedoor og ved søgning i Spatial Suite.

**Comment by furesoe** [comment]
@klavspc: 
@rastermanden:
Har I et overslag på dette? Det ser ud til, at der er flere kommuner, der finder muligheden meget anvendelig.

**Comment by markusroesgen** [comment]
Vi får flere og flere brugerhenvendelser om det og håber på en hurtig løsning. Hvad er status på det?

**Comment by klavspc** [comment]
Vi kan sagtens lave en søgning på vejnavn med visning af enten forløb eller ekstent

Det, der har stoppet os hidtil er kollisionen med adressesøgningen. Vil brugeren kunne forstå, at der står Æblevej to steder i resultat-listen, nemlig for adresser og for veje?

Ét forslag kunne være at det for en funden adresse skal være muligt at se vejresultat i f.eks. info-fanebladet og her kunne klikke på øjet for at se forløb og på selve resultatet for at komme til vej-resultat med egne faneblade, hvis det er nødvendigt

Ser frem til tilbagemelding og at specificeret den endelig løsing - så vil vi selvfølgelig følge op med estimat

**Comment by Ellebjerg** [comment]
Vi synes ikke om løsningen med, at man skal ind på en adresse først for at kunne komme til en given vej. Det er ulogisk og besværligt for brugerne.
Det naturlige vil være at vise vejen over adressesøgningen, så der man går fra det generelle (fx Høvedstensvej) til det mere specifikke (fx Høvedstensvej 1, Høvedstensvej 2 osv.).
![SPS søgning](https://user-images.githubusercontent.com/10741426/193016383-ca5a29a0-06d5-4c4f-a6bb-d27ac5e62177.png)

**Comment by furesoe** [comment]
Furesø Kommune vil gerne være med til at finansiere en løsning.
Vi har S4 og jeg tænker, at det gør det nemmere at lave en løsning som vi i Furesø er tilfredse med.

**Comment by klavspc** [comment]
@furesoe @Ellebjerg @markusroesgen 
Nu hvor vi har et vejresultat hvilke detaljer ville være oplagte til en detail handler? De sædvanlige konflikt-analyser (f.eks. lokalplaner) vil altid være til rådighed

**Comment by Ellebjerg** [comment]
Min umiddelbare tanke var adgangsadresser/husnumre, men ved veje med  mange adresser kan det nok blive voldsomt. Omvendt vil det give en naturlig forbindelse til resten af Onedoor.

Kobling til Vejman/RoSy er oplagt men knapt så umiddelbart implementerbare. Det kræver nøjere overvejelser om, hvilke data som skal med, og hvordan der smart linkes til selve systemerne. 
Ud fra mit begrænsede kendskab til RoSy og måden, det anvendes, kan vejene være opdelt på en masse selvstændige  registreringer ud fra bl.a. kilometrering osg sideveje. Måske kan vejreferencen være relevant.

**Comment by klavspc** [comment]
@furesoe @Ellebjerg @markusroesgen

Så er der et løsningsforslag i test - som beskrevet i [kommentaren ovenfor](https://github.com/Septima/OneDoor/issues/37#issuecomment-1262170888) så vil et vej-resultat blive vist i resultatlisten, hvis søgningen giver en entydig vej - meget lig S4
-  Prøv at skrive "høvedsten" https://onedoor.test.septima.dk/#/septima/lite - gælder selvfølgelig for alle veje; giv nogle forskellige søgninger et forsøg

Ligenu viser OneDoor vejforløb og et meget simpelt detalje-faneblad
-  Opret meget gerne andet issue, hvis vi skal se på noget Vejman/RoSy-integration - gerne med noget dokumentation på dees services

Se [denne tidligere kommentar](https://github.com/Septima/OneDoor/issues/37#issuecomment-1397187938) for hvordan funktionen konfigureres og man kan undgå ikke-relevante detaljer for veje

**Comment by Ellebjerg** [comment]
Jeg synes, at det ser fint ud på https://onedoor.test.septima.dk/#/septima/lite.

I forhold til evt. visning af husnumre, kan man så ikke gøre det i samme stil, som det gøres på ois.dk? Man kan fx lave links for 30 husnumre ad gangen, som brugerne så kan folde ud til visning af en liste og tilhørende kort med BBOX for de pågældende husnumre med mulighed for at vælge de enkelte husnumre. I Hvidovre ville visning for Hvidovrevej fx starte med et link 43A-84, 84A-97G... Husnumre under 43A ligger i Rødovre Kommune, så de er ikke interessante for os.

På en eller anden måde virker det underligt ikke at have en forbindelse fra vej til husnumre, så hvis det kan lade sig gøre nogenlunde nemt, vil det være godt.

Vi ser på den med kobling til RoSy og vender tilbage.

**Comment by klavspc** [comment]
> Man kan fx lave links for 30 husnumre ad gangen, som brugerne så kan folde ud til visning af en liste og tilhørende kort med BBOX for de pågældende husnumre med mulighed for at vælge de enkelte husnumre

OneDoor kan desværre ikke noget med at folde ind og ud. Jeg kan lave en simpel handler, der lister _alle_ husnumre i kommunen (For hvert husnummer vil man kunne klikke på enten husnummeret for at se detaljer eller på øjet) Skal jeg gøre det?

@furesoe @Ellebjerg @markusroesgen :
Jeg har brugt 12 timer til nu og en sådan handler vil bringe det op på 14-15 timer, dvs ca. 5 timer til hver af jer 3

**Comment by furesoe** [comment]
@klavspc 
Jeg synes, at det ser rigtigt godt ud, det hele. Og vejen som indgang, åbner en masse nye muligheder.
Du kan godt lave omtalte handler for mit vedkommende. Der er ok for 5 timers udvikling herfra.

En kobling til Vejman, vil fra min synsvinkel være rigtig god. Vi er dog ikke så langt med at udnytte mulighederne i Vejman og er først lige blevet færdige med VRD-projektet (vejreferencen). 

Derudover, hvor henter den geometrierne for vejmidterne henne? Det er stærkt at kunne se alle vejstykker der har samme fremsøgte navn/vejkode. Jeg synes dog ikke, at det stemmer helt overens med oplysningerne i GeoDanmark? Mange steder gør det, men andre steder ikke. Og jeg ville da tro, at det searcheren returnerer, er de vejstykker der har fået et navn og vejkode?

**Comment by Ellebjerg** [comment]
@klavspc @furesoe @markusroesgen 
Vi har lige taget en brainstorm på det, her i Hvidovre.

Først og fremmest vil vi meget gerne have vejkoden med i visningen, fx Hvidovrevej (4032), og så skal vi meget gerne kunne søge på vejkode.

I forhold til adresser foreslår vi en løsning, hvor der i kortet vises de adgangsadresser, som er knyttet til en fremsøgt vej med mulighed for at klikke på disse og blive sendt videre til "Om husnummeret", samt med mulighed for at tænde for vejpunkter og vejpunktlinjer for de viste adressepunkter. Funktionaliteten med vejpunkter og vejpunktlinjer findes bl.a. på https://danmarksadresser.dk/adresser-i-danmark, hvis der er nogle af jer, der ikke kender den.

I første omgang tror vi, at det bliver for omfattende at vise data fra RoSy/Vejman i Onedoor. Der er rigtig mange data i disse systemer. De er ikke nødvendigvis knyttet 1:1 til de vejstykker, som benyttes i GeoDanmark og dermed i Vejreferencen. Vi foreslår derfor, at der indsættes et link til vejadministrationssystemet på samme måde som til Filarkiv.

Til gengæld vil det give mening at vise attributter fra GeoDanmark. Det kunne fx være vejkategori, trafikart, vejmidtetype, vejmyndighed, cvfadmnr, overflade, rundkørsel, tilogfrakørsel, niveau, geometristatus, status, virkning fra, forretningsproces og kommentar.

**Comment by furesoe** [comment]
@klavspc @markusroesgen @Ellebjerg 

Jeg er meget enig i det, som @Ellebjerg skriver. Lad os vente med at integrere vejforvaltningssystemer.

Hvornår tror du, @klavspc , at der kan være noget klar til udrulning?

**Comment by klavspc** [comment]
@furesoe @Ellebjerg @markusroesgen

Jeg kan være klar i uge 6 (8. februar) med den funktionalitet i har set plus liste af husnumre på vejen

Andre ønsker må vi tage som separate issues

Lyder det ok?

**Comment by Ellebjerg** [comment]
Det lyder fint.

**Comment by furesoe** [comment]
> @furesoe @Ellebjerg @markusroesgen
> 
> Jeg kan være klar i uge 6 (8. februar) med den funktionalitet i har set plus liste af husnumre på vejen
> 
> Andre ønsker må vi tage som separate issues
> 
> Lyder det ok?

Det lyder helt fint, @klavspc

**Comment by klavspc** [comment]
Løst - kommer i næste release

For at se vejresultater som nævnt ovenfor så skal
-  option _showOneStreet_ sættes til _true_ på dawa-searcheren
-  detailhandleren `Septima.Search.HusnumreForVejProvider` tilknyttes dawa-searcheren

Komplet eksempel:
```
  _type: Septima.Search.DawaSearcher
  _options:
    minimumShowCount: 3
    showOneStreet: true
  detailhandlers:
    - _type: Septima.Search.HusnumreForVejProvider
```

**Comment by rastermanden** [comment]
goal: adgangellerenhedsadresse fungerer ikke.

**Comment by furesoe** [comment]
Det virker fint med den nye visning af husnumre for en vej. Det ville dog være godt hvis visningen modsvarede den der er når man kører handleren 'Husnumre inden for lokalplanen'.

Her summeres antallet af husnumre og der er derved kun én overskrift. 
Sådan fungerer det ikke for 'Husnumre for vejen'.

Se eksempler nedenfor
![image](https://user-images.githubusercontent.com/38730459/219034230-5641c1a5-79f3-4bb2-b810-cdd495e7b457.png)

![image](https://user-images.githubusercontent.com/38730459/219034803-fc38a03b-a7db-410e-a592-032932cd9af7.png)

Kan det gøres på samme måde @klavspc ?

**Comment by klavspc** [comment]
>Det ville dog være godt hvis visningen modsvarede den der er når man kører handleren 'Husnumre inden for lokalplanen'.

Enig

Jeg fikser det sammen med den fejl @rastermanden fandt tidligere:
>goal: adgangellerenhedsadresse fungerer ikke.

**Comment by klavspc** [comment]
Fikset i SS 5.55.13+

**Comment by klavspc** [comment]
>Det ville dog være godt hvis visningen modsvarede den der er når man kører handleren 'Husnumre inden for lokalplanen'.

Fixet:
![image](https://user-images.githubusercontent.com/3736091/221585436-d9cbfacc-2deb-40e8-b570-35398da0b049.png)

**Comment by klavspc** [comment]
> goal: adgangellerenhedsadresse fungerer ikke.

Vej vises nu uanset om dawa er sat til at søge på husnumre, adresser eller begge

**Comment by Ellebjerg** [comment]
Virker fint, inkl. veje uden adresser.
