### ISSUE TITLE
Plannr-tilføjelse til lokalplan-resultatvisningen

### ISSUE THREAD

**Issue by furesoe** [Septima/OneDoor#38]
Det er efterspurgt af byplanlæggere og byggesagsbehandlere, at resultatvisningen for vedtagne lokalplaner også indeholder plannummer.

Fx vil det være ideelt, hvis der for nedenstående kunne stå: L.116 - Hareskovby - Boligområde .

http://furesoeg/#/furesoe/ejendomsperspektiv/Dawa/adresse/0a3f507e-3d25-32b8-e044-0003ba298018/omhusnummer

![image](https://user-images.githubusercontent.com/38730459/169862435-c1997e78-601c-418a-9bd2-5bb4ef32916c.png)

Kan det imødekommes?

**Comment by rastermanden** [comment]
I søgefeltet ståt det allerede sådan her:

![image](https://user-images.githubusercontent.com/1125134/186113047-7137ca7a-f113-47f5-840b-4736ee504330.png)

Så vil der i dette tilfælde komme til at stå (title - description): Harreskovby - Planummer: L.116 - Boligområde

Det bør i hvertfald stå ens begge steder. Så spørgsmålet er om plannummer hører til i title eller description. Hører gerne meninger om dette

**Comment by rastermanden** [comment]
Er lavet og kommer med i næste release:

![image](https://user-images.githubusercontent.com/1125134/186149410-74311fd6-3361-4198-baaf-b817a401cd56.png)
