### ISSUE TITLE
Vis data fra BBRsag

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#46]
Det ville være godt, hvis der ved søgning på adresse, matrikel m.m. kunne vises aktuelle byggesager i OneDoor. De må kunne trækkes fra BBRsag, som udstilles af Datafordeler.
Hvis dette kunne gøres, vil link til KMD Nova (issue #15) ikke være helt så vigtigt. I hvert fald vil der skulle ses på, om det er værd at bruge ressourcer på.

**Comment by rastermanden** [comment]
Sådan ser data ud fra DAF:

```sql

[
  {
    "datafordelerOpdateringstid": "2021-04-01T22:20:48.427816+02:00",
    "forretningshændelse": "Byggesag",
    "forretningsområde": "54.15.05.05",
    "forretningsproces": "11",
    "id_lokalId": "0de5b1a8-97af-49a2-abd7-3f455d34d3e2",
    "id_namespace": "http://data.gov.dk/bbr/bbrsag",
    "kommunekode": "0101",
    "registreringFra": "2018-02-16T18:58:00.000119+01:00",
    "registreringsaktør": "BBR",
    "sag001Byggesagsnummer": "704732",
    "sag002Byggesagsdato": "2017-10-27T00:00:00.000000+02:00",
    "sag003Byggetilladelsesdato": "2017-10-27T00:00:00.000000+02:00",
    "sag005Påbegyndelsesdato": "2017-10-31T00:00:00.000000+01:00",
    "sag006IbrugtagningsTilladelse": "2017-12-14T00:00:00.000000+01:00",
    "sag010FuldførelseAfByggeri": "2017-11-14T00:00:00.000000+01:00",
    "sag012Byggesagskode": "3",
    "sag024DatoForModtagelseAfAnsøgningOmByggetilladelse": "2017-06-28T00:00:00.000000+02:00",
    "sag025DatoForFyldestgørendeAnsøgning": "2017-06-28T00:00:00.000000+02:00",
    "sag032Litra": "",
    "status": "9",
    "virkningFra": "2017-12-15T08:00:02.662871+01:00",
    "virkningsaktør": "Registerfører",
    "sagsniveauList": [
      {
        "id_lokalid": "e8102929-2964-4706-b5d1-e88f6ce95052",
        "sagsniveau": {
          "datafordelerOpdateringstid": "2021-04-04T03:43:32.781031+02:00",
          "byggesag": "0de5b1a8-97af-49a2-abd7-3f455d34d3e2",
          "forretningshændelse": "Byggesag",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "11",
          "id_lokalId": "e8102929-2964-4706-b5d1-e88f6ce95052",
          "id_namespace": "http://data.gov.dk/bbr/sagsniveau",
          "kommunekode": "0101",
          "niveautype": "2",
          "registreringFra": "2017-12-15T08:00:02.662871+01:00",
          "registreringsaktør": "BBR",
          "sagsdataBygning": "4a5074b4-f1ee-44ff-a6bf-20dc577c90bc",
          "sagstype": "2",
          "stamdataBygning": "9a837c75-a4d4-4a0a-8379-0b76ab654265",
          "status": "9",
          "virkningFra": "2017-12-15T08:00:02.662871+01:00",
          "virkningsaktør": "BBR"
        }
      }
    ]
  },
  {
    "datafordelerOpdateringstid": "2021-04-01T22:57:14.729965+02:00",
    "forretningshændelse": "Byggesag",
    "forretningsområde": "54.15.05.05",
    "forretningsproces": "11",
    "id_lokalId": "f5022eeb-f359-4bb3-bd22-9651de0db32f",
    "id_namespace": "http://data.gov.dk/bbr/bbrsag",
    "kommunekode": "0101",
    "registreringFra": "2020-01-20T13:49:03.903942+01:00",
    "registreringsaktør": "BBR",
    "sag001Byggesagsnummer": "712475",
    "sag002Byggesagsdato": "2018-08-02T00:00:00.000000+02:00",
    "sag003Byggetilladelsesdato": "2018-08-02T00:00:00.000000+02:00",
    "sag005Påbegyndelsesdato": "2018-09-18T00:00:00.000000+02:00",
    "sag006IbrugtagningsTilladelse": "2020-01-17T00:00:00.000000+01:00",
    "sag010FuldførelseAfByggeri": "2020-01-09T00:00:00.000000+01:00",
    "sag012Byggesagskode": "3",
    "sag024DatoForModtagelseAfAnsøgningOmByggetilladelse": "2018-05-29T00:00:00.000000+02:00",
    "sag025DatoForFyldestgørendeAnsøgning": "2018-07-04T00:00:00.000000+02:00",
    "status": "9",
    "virkningFra": "2020-01-20T13:49:03.903942+01:00",
    "virkningsaktør": "Registerfører",
    "sagsniveauList": [
      {
        "id_lokalid": "b1c49c96-2a06-4a52-9cfe-08f418a9e3f6",
        "sagsniveau": {
          "datafordelerOpdateringstid": "2021-04-04T04:08:44.366182+02:00",
          "byggesag": "f5022eeb-f359-4bb3-bd22-9651de0db32f",
          "forretningshændelse": "Byggesag",
          "forretningsområde": "54.15.05.05",
          "forretningsproces": "11",
          "id_lokalId": "b1c49c96-2a06-4a52-9cfe-08f418a9e3f6",
          "id_namespace": "http://data.gov.dk/bbr/sagsniveau",
          "kommunekode": "0101",
          "niveautype": "2",
          "registreringFra": "2020-01-20T13:49:03.903942+01:00",
          "registreringsaktør": "BBR",
          "sagsdataBygning": "d8e6d79b-d83f-45b1-aea3-b13e9d0f1080",
          "sagstype": "2",
          "stamdataBygning": "9a837c75-a4d4-4a0a-8379-0b76ab654265",
          "status": "9",
          "virkningFra": "2020-01-20T13:49:03.903942+01:00",
          "virkningsaktør": "BBR"
        }
      }
    ]
  }
]

```

**Comment by rastermanden** [comment]
Er denne stadig relevant ?

**Comment by Ellebjerg** [comment]
Det synes jeg bestemt, at den er. Det er kun relevant at vise, hvis er er en igangværende byggesag (er det "status", der afgør det?). Det vil være relevant at vise 
byggesagsnummer (sag001Byggersagsnummer), 
diverse datoer (sag002..., sag003... osv. sag010FuldførelseAfByggeri er ikke relevant, for så vil byggesagen ikke længere være aktiv)
byggesagskode (sag012Byggesagskode)
status (status) - Jeg kan ikke finde en kodeliste for denne variabel, men der må være alle status, som ikke er afsluttet eller aflyst
sagstype
Muligvis niveautype-

**Comment by rastermanden** [comment]
Man kan få fremsægt sager på bygningsid: https://confluence.sdfi.dk/pages/viewpage.action?pageId=16056582#REST(BBR)-Metode-bbrsag

Det vil sige at man på en bygning kan lave en fane med byggesager og få vist de relevante kolonner samt oversat kodelistener.

Det kan laves på 4-5 timer.
 
Hvis der skal aggegres på matrikelniveau eller andre ting er det lidt mere kompliceret, men der nokm muligheder

kodelister for status, sagstype, niveatype kan oversættes her:

https://teknik.bbr.dk/kodelister/0/1/0/Livscyklus
https://teknik.bbr.dk/kodelister/0/1/0/NiveauType
https://teknik.bbr.dk/kodelister/0/1/0/Sagstype

**Comment by rastermanden** [comment]
Kan vise data fra ovenstående undtagen "sagsniveauList" array

**Comment by rastermanden** [comment]
Skal vi gå videre med denne ?

**Comment by Ellebjerg** [comment]
Hvis man ser på https://confluence.sdfi.dk/pages/viewpage.action?pageId=16056582#REST(BBR)-Metode-bbrsag, er der et felt, som hedder Grund. Det er, så vidt vi kan se, de grunde, som sagen/bygningen vedrører. Det er mere interessant at opgøre sagerne på grund som primær fremsøgning, da fx nybyggeri på en tom grund ikke vil have en bygnings-id tilknyttet før ganske langt inde i processen.

**Comment by rastermanden** [comment]
Man ville også kunne:

- For et husnummer, finde de sager, der hører til den grund husnummeret hører til
- For et jordstykke, finde de sager, som jordstykkets grund hører til

**Comment by Ellebjerg** [comment]
Kan det gøres på de 4-5 timer, som du angiver ovenfor?

**Comment by rastermanden** [comment]
Nej, der er mere arbejde i det end som så.

For et husnummer skal man feks. først finde den tilhørende ejendoms grund

Jeg tro det kan gøres på 7-8 timer

**Comment by rastermanden** [comment]
@Ellebjerg, fandt I ud af mere om links til [NOVA sag](https://github.com/Septima/OneDoor/issues/15)?

**Comment by GISAabenraa** [comment]
Hej Martin, Lars og Mikael.
Hvor mange timer skal vi bidrage med hver især, hvis Aaabenraa skal være med?
Måske er Sønderborg og Varde også interesseret - spørge dem lige

**Comment by rastermanden** [comment]
3-4 timer

Hvis flere er med, er det naturligvis mindre.

**Comment by GISAabenraa** [comment]
Aabenraa Kommune er med.
