### ISSUE TITLE
Fejl i enhedsadresser

### ISSUE THREAD

**Issue by emilbang** [Septima/OneDoor#6]
Fejl:
Mange enhedsadresser kan ikke søges frem (får fejl), mens nogle stadig kan. Fx fejler Smallegade 1,1. mens Mariendalsvej 23A, st. 104 virker. Vi får denne fejl:
S3Error: Cannot read property 'enh020EnhedensAnvendelse' of undefined

Vi kan ikke genskabe det på septima.onedoor.dk fordi det ikke virker som om den søger i enhedsadresser.

**Comment by rastermanden** [comment]
Fejlen skyldes, at første fane I jeres opsætning viser BBr info som har en fejl.

**Comment by rastermanden** [comment]
Denne burde være løst. Vil du teste om det ikke er tilfældet ?
