### ISSUE TITLE
OneDoor til QGIS virker ikke i QGIS v. 3.30.0

### ISSUE THREAD

**Issue by MichaelDavidKnudsen** [Septima/OneDoor#61]
Hej

Seneste version af OneDoor  (hentet på Septimas hjemmeside 24. april 2023) virker ikke i QGIS Version v. 3.30.0.

Der kan bl.a. ikke søges på matrikel og kortet følger ikke med på en række data.

Under installationen fås følgende fejl, men efterfølgende melder QGIS at installationen er succesfuld.
![image](https://user-images.githubusercontent.com/8234702/234254179-dee75631-5f72-46c8-8815-d91b6c69806c.png)

vh. Michael

**Comment by Ellebjerg** [comment]
Jeg får heller ikke fejl i installationen på Windows, men jeg oplever samme funktionsfejl som Michael og Martin i QGIS 3.30, men ikke i 3.28.

**Comment by klavspc** [comment]
@MichaelDavidKnudsen @Ellebjerg @rastermanden :

Prøv denne version for at se om I kan få vist resultater med Polygon-geometri (Det var dét, der var problemet)
[septima-onedoor-qgis-plugin-0.2.21.zip](https://github.com/Septima/OneDoor/files/11626493/septima-onedoor-qgis-plugin-0.2.21.zip)

**Comment by GISAabenraa** [comment]
Hermed bekræfter vi også at det virker. Tak.
