### ISSUE TITLE
Ejerdata

### ISSUE THREAD

**Issue by GISAabenraa** [Septima/OneDoor#68]
Hej Septima.

Det er måske det forkerte sted at skrive det issue, men jeg ligger det alligevel her, så kan måske andre kunder ser det samme behov.

Vi har en fane Ejendom, men kan man få oplysninger om alle "tidligere ejere" af ejendommen i OneDoor?

I lukker bare hvis de er irrelevant.

**Comment by rastermanden** [comment]
Det lyder spændende. Vi vil undersøge mulighederne

**Comment by GISAabenraa** [comment]
Der er nogle oplysninger, som bruges meget ofte i miljøforureningssager.

**Comment by GISAabenraa** [comment]
Har I kigget på muligheden?

**Comment by rastermanden** [comment]
Vi har ikke kigget på det endnu. Men det burde være muligt at trække tidligere ejere fra Datfordeleren

**Comment by rastermanden** [comment]
Der er muligheder for det. Det kan være både personer og virksomheder, som har ejet en ejendom.

Derudover er der muligvis også historiske administratorer.

Er der andre der kunne have interesse i dette ?

Vi kan lave et estimat og Septima bidrager også gerne med timer

**Comment by GISAabenraa** [comment]
Vi er i hvert fald med :)

**Comment by rastermanden** [comment]
Opgaven er estimeret til 8 timer.

**Comment by Ellebjerg** [comment]
Vi vil også gerne være med

**Comment by rastermanden** [comment]
Hvis @GISAabenraa og @Ellebjerg leverer 2.5 timer hver, lægger Septima resten.

Er det en aftale ?

**Comment by Ellebjerg** [comment]
Jeg leverer ikke timer, men Hvidovre gør gerne 😉

**Comment by GISAabenraa** [comment]
Aabenraa gør også :)

**Comment by rastermanden** [comment]
Glimrende. Jeg sørger for den er lavet og kommer med i en ny version snarest.

**Comment by GISAabenraa** [comment]
Det virker fint. Skal issuet lukkes?

**Comment by rastermanden** [comment]
ja
