### ISSUE TITLE
Noter vedr lokalplansøgning

### ISSUE THREAD

**Issue by klavspc** [Septima/OneDoor#69]
OneDoor burde fange både ”lokalplan 113” og ” lp 113” og ikke kun LP13.

I det mindste skal ”113” fanges når man står på Vedtagne lokalplaner

 
![image](https://github.com/Septima/OneDoor/assets/3736091/91a9b9dc-7699-4f14-9d12-67aa04d7e908)

**Comment by GISAabenraa** [comment]
Hej Klavs

Denne dublerer issuet https://github.com/Septima/OneDoor/issues/63
Skal det gamle issue ikke lukkes ?

MVH Nicolai

**Comment by rastermanden** [comment]
dublet
