### ISSUE TITLE
produktionsenheder ikke georefereret 

### ISSUE THREAD

**Issue by emilbang** [Septima/OneDoor#7]
Nogle virksomheder vises ikke på kort når de vælges, selv om adressen står i resultatvinduet. Linjen med adressen bliver ikke vist, så det er nok der fejlen ligger.

fx https://onedoor.septima.dk/#/septima/standard/cvr/produktionsenhed/1016221305/Septima.Search.CvrInfoProvider_1

**Comment by rastermanden** [comment]
En meget større del georeferes nu i version 1.4.24
