### ISSUE TITLE
Fejl i URL-kaldet under "Offentlige links"

### ISSUE THREAD

**Issue by GISAabenraa** [Septima/OneDoor#70]
### Boligejer.dk 
URL kald der sendes https://boligejer.dk/ejendomsdata?**knr**=0580&**enr**=xxxx
men det rigtige kald er  https://boligejer.dk/ejendomsdata?**kommuneId**=0580&**ejendomId**=xxxx

### BBR-meddelelse
https://bbr.dk/pls/wwwdata/**get_ois_pck.show_bbr_meddelelse_pdf**?i_municipalitycode=0580&i_realpropertyidentifier=xxxx
_The procedure named get_ois_pck.show_bbr_meddelelse_pdf could not be accessed_

Skal/Kan vi selv rette det i konfigurationen? Eller har vi mistet en opdatering af OneDoor?

**Comment by rastermanden** [comment]
Boligejer.dk fungerer i seneste version.
Undersøger BBR

**Comment by GISAabenraa** [comment]
Tror godt det er fikset i sidste version (v 1.9.2) , så de links bliver styret centralt af Septima på en måde. 
Kan det passe?

**Comment by rastermanden** [comment]
ja, den er med i seneste version
