### ISSUE TITLE
Fejl i links til Samlet Fast Ejendom

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#72]
Når vi efter søgning på adresse klikker på et BFE-link i _Samlet Fast Ejendom_, får vi fejlen

Unexpected error
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Vh Lars

**Comment by Ellebjerg** [comment]
Jeg ved ikke, om det er samme fejl, men under _Boliger på husnummeret_ står der følgende:

Der skete en fejl
https://services.datafordeler.dk/BBR/BBRPublic/1/REST/Enhed?status=6&Opgang=087cc518-7246-492c-835c-cfaa5418d4b1 Failed: read ECONNRESET

**Comment by GISAabenraa** [comment]
Vi har oplevet tilsvarende.
Kan det være fejl med det nye OCES3 certifikat?

Hos os var fejlen at kodeordet til den nye certifikat skulle står i gåsetegn "**password**" muligvis p.g.a. nogle specielle symboler i kodeordet.

**Comment by Ellebjerg** [comment]
Certifikat på plads, så nu virker det.
