### ISSUE TITLE
Skoledistrikter

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#75]
Ved søgning efter skoledistrikter med tegneværktøjet i det store kort mangler I at filtrere, så det kun er vedtagne distrikter, der vises, og så det kun er skoledistrikter. Alternativt kan der vises både forslag, vedtagne og aflyste distrikter, men så skal status fremgå.

![image](https://github.com/Septima/OneDoor/assets/10741426/f9c97ba6-ba3a-42d6-9d6b-233dd07bec02)

**Comment by rastermanden** [comment]
I nsæte version er der status med i description
