### ISSUE TITLE
Dyblink til BBR virker ikke

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#76]
Links til BBR-kommune leder til en blank side med besked "Ingen søgning foretaget", uanset om der vælges _Se bygning_ eller _Se grund_.

**Comment by rastermanden** [comment]
Er der logget ind i BBR-kommune ?

**Comment by Ellebjerg** [comment]
Ja, jeg er logget ind.

**Comment by rastermanden** [comment]
ok. URL'et må været lavet om.

Vi har ikke login. Hvis du kan fremskaffe url'erne må du meget gerne det.

**Comment by Ellebjerg** [comment]
Grund: https://kommune.bbr.dk/bob/GRU/dee1f531-770d-4d92-9bbe-a1f17259416f
Bygning: https://kommune.bbr.dk/bob/BYG/7aff6a0d-772a-4688-b17e-ee3dfcfc20a0

**Comment by rastermanden** [comment]
Har lagt det på i http://test-onedoor.hvidovre.dk/

Vil du test og se om det virker
