### ISSUE TITLE
Aktivering af "udskriv" rapport funktion

### ISSUE THREAD

**Issue by rastermanden** [Septima/OneDoor#77]
Hvis I mangler "udskriv" knappen:
![image](https://github.com/Septima/OneDoor/assets/1125134/9528f938-84c8-4c7f-859f-a6396a8701ea)

SkaI I filen service.bat i jeres website folder tilføje følgende så indholdet ser således ud:

```
SET ALLOW_REPORT=true
node .
```

Og derefter genstarte servicen

**Comment by Ellebjerg** [comment]
Hvor finder vi service.bat?

**Comment by rastermanden** [comment]
Den skal ligge i roden af jeres site-folder f.ek.s: c:\septima\sites\myonedoor.dk\service.bat

Hvis I manlger en service.bat så kan jeg hjælpe

**Comment by Ellebjerg** [comment]
Den mangler vi vist, så du må meget gerne gå på og ordne det, som skal ordnes.
