### ISSUE TITLE
Fejl i layout for kortvisning af det store kort

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#80]
Hos os er der opstået en fejl i visningen af det store kort. 
Der er kommet en hvid bjælke ind mellem den blå topbjælke og kortet, hvilket i sig selv ikke er hensigtsmæssigt, men det er helt galt fordi, at kortet har stadig størrelse til at udfylde hele browservinduet under den blå bjælke, så nu skal man scrolle ned for at se det nederste af kort og legend. Fejlen er der i både Chrome og Edge.

![Billede1](https://github.com/Septima/OneDoor/assets/10741426/d6f6370c-ec35-4869-abb7-7da6cc30fcfc)

**Comment by rastermanden** [comment]
Det er fordi I har custom.css
Er rettet hos jer nu

**Comment by Ellebjerg** [comment]
Hvilken del af config skal vi kopiere til driftskortet for at få det løst der?
