### ISSUE TITLE
Info om produktionsenheder

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#83]
Det ville være rart med lidt mere info om produktionsenheder i søgeresultatet. Hvis jeg fx søger på Netto, får jeg det viste resultat, hvorefter jeg skal til at klikke mig igennem resultatlisten, til jeg finder den enhed. Jeg leder efter. Adresse eller lignende ville være en hjælp.

![Skærmbillede 2023-12-11 151652](https://github.com/Septima/OneDoor/assets/10741426/3061c1ba-a0fb-4362-a716-2554cdfb8ae0)

**Comment by rastermanden** [comment]
Adressen er med i kommende version as onedoor
