### ISSUE TITLE
Husnummer og bygning

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#84]
Vi har en bygning på Beringgårdsvej 41A og 41B, som i GeoDanmark er angivet som 'Under anlæg' og i BBR som nybyggeri. Men i OneDoor angives det, at husnummeret ikke ligger i en bygning, selv om husnummeret ligger i en bygning, som findes i såvel GeoDanmark som BBR, om end ikke som anlagt. Det vil være hensigtsmæssigt, hvis også bygninger under anlæg kommer med i resultaterne i OneDoor, da disse netop er ekstra relevante ift. forskellige kommunale administrative opgaver.

![Skærmbillede 2024-02-15 095357](https://github.com/Septima/OneDoor/assets/10741426/aa4c06ba-e6ca-411e-b98a-40241d8c1d7d)

**Comment by rastermanden** [comment]
Vi undersøger sagen snarest og ser hvad mulighederne er

**Comment by rastermanden** [comment]
Bygningerne i onedoor hentes på baggrund af statuskoder (livscyklus). Som det er nu, visers kun koderne 6,12,13
![image](https://github.com/Septima/OneDoor/assets/1125134/c9c27c63-a644-4f9c-bde9-95feb5ce412f)

**Comment by Ellebjerg** [comment]
Kode 3 vil være hensigtsmæssig at få med

**Comment by klavspc** [comment]
Bygninger med status 3 (Under opførsel) medtages

Bygningers status inkluderes i parentes i bygningens titel:
![image](https://github.com/Septima/OneDoor/assets/3736091/f0cdcb66-63f8-40b6-8e13-99bcd22868fe)
