### ISSUE TITLE
Fejl i planer for BFE 2077926

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#88]
Når jeg søger på Muslingevej 35, får jeg vist planer korrekt for adressen, men klikker jeg mig videre til ejendommen BFE 2077926, angives der "Ingen planer fundet".

Jeg har testet på 2-3 andre adresser, bl.a. Muslingevej 33 og 37. Her vises planerne helt fint både under adressen og under ejendommen.

Lars

**Comment by rastermanden** [comment]
Undersøger sagen

**Comment by rastermanden** [comment]
Det er rettet i standardkonfifurationen i seneste version. Det var en forkert buffer på søgegeomtrien
