### ISSUE TITLE
Søgehits uhensigtsmæssigt, daginstitutioner

### ISSUE THREAD

**Issue by cfischer00** [Septima/OneDoor#94]
Overtaget fra: https://github.com/Septima/OneDoor/issues/63

Der flere eksempler på problemet

![image](https://github.com/user-attachments/assets/950f9c90-9d63-494d-8cbe-f329ca8401a2)

![image](https://github.com/user-attachments/assets/168d1e73-a75a-463d-9365-12db76303b0f)

Hvorfor kommer der ingen match ved første søgning?

**Comment by cfischer00** [comment]
Fungerer nu

**Comment by cfischer00** [comment]
@GISAabenraa : Dette issue har jeg udskilt fra https://github.com/Septima/OneDoor/issues/63

Vil du verificere at POI-søgningerne også fungerer bedre nu?

**Comment by GISAabenraa** [comment]
Det kan jeg godt bekræfte.
