### ISSUE TITLE
Adresse kan ikke fremsøges

### ISSUE THREAD

**Issue by Ellebjerg** [Septima/OneDoor#96]
Jeg har ændret adressen Vigerslev Alle 375 til Vigerslevvej 236, og nu kan jeg ikke søge nogen af adresserne frem, selv om ændringen er slået igennem i DAR, og det nye husnummer vises i kortet.

Adressepunktet ligger i Hvidovre, men Vigerslevvej findes ikke i kommunen, så det tilhørende vejpunkt ligger i København.

**Comment by Ellebjerg** [comment]
![Skærmbillede 2024-10-28 145817](https://github.com/user-attachments/assets/db88ac42-2fa0-440c-ac7c-c23ca28d233c)

**Comment by cfischer00** [comment]
@Ellebjerg : Jeg kan godt finde Vigerslevvej 236.

Vil du prøve igen? Det er måske noget opdatering på dataforsyningen (Dawa), der ikke har været hurtige nok. Den blev oprettet på datafordeleren kl. 10:30 i går.

**Comment by cfischer00** [comment]
Ja - jeg tror nu mere det er opdateringen på dawa, der er den service der ligger bag dataforsyningen.

DAF tilbyder ikke type-ahead søgninger på adresser
